#!/bin/bash
##Version 1.0.2-1
#
#License: GPL2
#
#Author: Andy Crowd
#Tested in Arch Linux
#Search in *.desktop for "Categories" and "Exec"
#
DskPath[0]="/usr/share/applications/"
DskPath[1]="$HOME/.local/share/applications/"

DskPath[2]="/usr/local/share/applications"

DskPath[3]="/etc/xdg/autostart/"
DskPath[4]="$HOME/.config/autostart/"

DskPath[5]="$XDG_CONFIG_DIRS/autostart/"
DskPath[6]="$XDG_CONFIG_HOME/autostart/"

DskPath[7]="/usr/share/gnome/autostart/"

#### Search with no subdirs
MaxDepth[8]="-maxdepth 1"
DskPath[8]="$HOME/Desktop"
####

DskPath[9]="/usr/etc/xdg/autostart/"
DskPath[10]="/usr/share/mimelnk/application/"
DskPath[11]="/usr/share/mimelnk/chemical/"
DskPath[12]="/usr/lib/libreoffice/share/xdg/"
DskPath[13]="/usr/share/xsessions/"
DskPath[14]="/usr/share/apps/kdm/sessions/"
DskPath[15]="/usr/share/gdm/greeter/autostart/"
DskPath[16]="/usr/share/wayland-sessions/"
DskPath[17]="/usr/share/apps/kdm/programs/"
DskPath[18]="/usr/share/mate/wm-properties/"

Count=0

while [ $Count -lt ${#DskPath[@]} ];do

[[ -d "${DskPath[Count]}"  ]] && printf "\e[1;36m ${DskPath[Count]} \e[0m \n";

if [ ! -z "$1" ] && [ -d "${DskPath[Count]}" ] ;
  then 
   find "${DskPath[Count]}" ${MaxDepth[Count]}  -iname "*.desktop" -exec awk -v Fil="{}"  -v Seek="$1" -F"=" '//{
if(index($1,"Categories")) 
 Ctgr=$2;
if(index($0,"Name=" ) == 1) inNm=$2;
if(index($1,"Exec") == 1)   inExc=substr($0,index($0,"Exec")+5);
}END{
  split(inExc,Arr,"%");
  gsub(/[^*]*\//,"",Fil);
if(! Ctgr ){E=inNm}else{E=Ctgr};
 Z=Arr[1]" ¤ "E" ¤ "Fil;
if( index(tolower(Z),tolower(Seek)) && inExc  )  print Z;}' "{}" \;
fi;


if [[ -z "$1" && -d "${DskPath[Count]}" ]];
  then 
   find "${DskPath[Count]}" -iname "*.desktop" -exec awk -v Fil="{}"  -F"=" '//{
if(index($1,"Categories"))
 Ctgr=$2;
if(index($0,"Name=") == 1)
 inNm=$2;
if(index($1,"Exec") == 1)
 inExc=substr($0,index($0,"Exec")+5);
}END{
  split(inExc,Arr,"%");
  gsub(/[^*]*\//,"",Fil);
if(! Ctgr )
 {E=inNm}
  else
 {E=Ctgr};
 Z=Arr[1]" ¤ "E" ¤ "Fil;
if( inExc ) print Z;}' "{}" \;
fi;

Count=$((Count+1))
done
