#!/bin/bash
##Version 1.0.1-1
#
#License: GPL2
#
#Author: Andy Crowd
#Tested in Arch Linux
#Search in *.desktop for "Categories" and "Exec"
#
DskPath[0]="/usr/share/applications/"
DskPath[1]="$HOME/.local/share/applications/"

DskPath[2]="/etc/xdg/autostart/"
DskPath[3]="$HOME/.config/autostart/"

DskPath[4]="$XDG_CONFIG_DIRS/autostart/"
DskPath[5]="$XDG_CONFIG_HOME/autostart/"

Count=0

while [ $Count -lt ${#DskPath[@]} ];do

[[ -d "${DskPath[Count]}"  ]] && printf "\e[1;36m ${DskPath[Count]} \e[0m \n";

if [ ! -z "$1" ] && [ -d "${DskPath[Count]}" ] ;
  then
   find "${DskPath[Count]}" -iname "*.desktop" -exec awk -v Fil="{}"  -v Seek="$1" -F"=" '//{
if(index($1,"Categories"))
 Ctgr=$2;
if(index($0,"Name=" ) == 1)
 inNm=$2;
if(index($1,"Exec") == 1)inExc=substr($0,index($0,"Exec")+5);
}END{
  split(inExc,Arr,"%");
  gsub(/[^*]*\//,"",Fil);
if( ! Ctg){E=inNm}else{E=Ctgr};
 Z=Arr[1]" ¤ "E" ¤ "Fil;
if(match(tolower(Z),tolower(Seek)) ){
 print Z;};}' "{}" \;
fi;

if [[ -z "$1" && -d "${DskPath[Count]}" ]];
  then
   find "${DskPath[Count]}" -iname "*.desktop" -exec awk -v Fil="{}"  -F"=" '//{
if(index($1,"Categories"))
 Ctgr=$2;
if(index($0,"Name=") == 1)
 inNm=$2;
if(index($1,"Exec") == 1)
 inExc=substr($0,index($0,"Exec")+5);
}END{
  split(inExc,Arr,"%");
  gsub(/[^*]*\//,"",Fil);
if(! Ctgr)
 {E=inNm}
  else
 {E=Ctgr};
 Z=Arr[1]" ¤ "E" ¤ "Fil;
 print Z;}' "{}" \;
fi;
Count=$((Count+1))
done
